#!/usr/bin/env python

## @file CloudMsgs/__init__.py
#
#  @package CloudServices
#


from FaceDetection import FaceDetection
from QrDetection import QrDetection
from SpeechRecognitionSphinx import SpeechRecognitionSphinx
from SpeechRecognitionGoogle import SpeechRecognitionGoogle
from SetNoiseProfile import SetNoiseProfile
from OntologySubclasses import OntologySubclasses
from OntologySuperclasses import OntologySuperclasses
from OntologyIsSubsuperclass import OntologyIsSubsuperclass
from TextToSpeech import TextToSpeech
from HumanDetection import HumanDetection
from CognitiveExerciseSelect import CognitiveExerciseSelect
from CognitiveRecordPerformance import CognitiveRecordPerformance
from CognitiveGetScores import CognitiveGetScores
from CognitiveGetHistory import CognitiveGetHistory
from EmailSend import EmailSend
from EmailFetch import EmailFetch
from NewsExplore import NewsExplore
from Geolocation import Geolocation
from WeatherReportCurrent import WeatherReportCurrent
from WeatherReportForecast import WeatherReportForecast
from ObjectRecognitionCaffe import ObjectRecognitionCaffe
from HazardDetectionDoor import HazardDetectionDoor
from HazardDetectionLight import HazardDetectionLight
from PathPlanningUploadMap import PathPlanningUploadMap
from PathPlanningPlan2D import PathPlanningPlan2D
from ObjectDetectionFindObjects import ObjectDetectionFindObjects
from ObjectDetectionClearModels import ObjectDetectionClearModels
from ObjectDetectionLoadModels import ObjectDetectionLoadModels
from ObjectDetectionLearnObject import ObjectDetectionLearnObject
from VisualLocalization import VisualLocalization
from VisualLocalizationInit import VisualLocalizationInit
from UserPersonalInfo import UserPersonalInfo
