// cloud basic services
#include "cloud/available_services/available_services.hpp"
#include "cloud/ontology/ontology.hpp"
#include "cloud/vision/face_detection/face_detection.hpp"
#include "cloud/vision/hazard_detection/hazard_detection.hpp"
#include "cloud/vision/human_detection/human_detection.hpp"
#include "cloud/vision/object_recognition/object_recognition.hpp"
#include "cloud/vision/qr_detection/qr_detection.hpp"
#include "cloud/speech/set_denoise_profile/set_denoise_profile.hpp"
#include "cloud/speech/speech_detection_google/speech_detection_google.hpp"
#include "cloud/speech/speech_detection_sphinx4/speech_detection_sphinx4.hpp"
#include "cloud/speech/text_to_speech/text_to_speech.hpp"
